const cardList = [
    {
        id: 1,
        name:"Knight",
        type:"adventurer",
        element:"Fire",
        attribute:["tank", "swordplay"],
        healthy_attack:"2",
        healthy_defense:"3",
        injured_attack:"0",
        injured_defense:"2",
        flavor:"I'll Protect you",
        description:"",
        turn_cost:"1",
        hand_cost:"0",
        effect:""
    },
    {
        id: 2,
        name:"Thaumaturge",
        type:"adventurer",
        element:"Fire",
        attribute:["dps", "mage"],
        healthy_attack:"3",
        healthy_defense:"0",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"This spell will show you",
        description:"",
        turn_cost:"0",
        hand_cost:"0",
        effect:""
    },
    {
        id: 3,
        name:"Cleric",
        type:"adventurer",
        element:"Fire",
        attribute:["healer", "mage"],
        healthy_attack:"0",
        healthy_defense:"1",
        injured_attack:"0",
        injured_defense:"0",
        flavor:"I'll take care of you",
        description:"",
        turn_cost:"0",
        hand_cost:"0",
        effect:""
    },
    {
        id: 4,
        name:"Swordsman",
        type:"adventurer",
        element:"Fire",
        attribute:["dps", "swordplay"],
        healthy_attack:"3",
        healthy_defense:"2",
        injured_attack:"1",
        injured_defense:"1",
        flavor:"En Garde",
        description:"",
        turn_cost:"1",
        hand_cost:"0",
        effect:""
    },
    {
        id: 5,
        name:"Myrmidon",
        type:"adventurer",
        element:"Fire",
        attribute:["tank"],
        healthy_attack:"1",
        healthy_defense:"3",
        injured_attack:"1",
        injured_defense:"1",
        flavor:"For my lord",
        description:"",
        turn_cost:"1",
        hand_cost:"0",
        effect:""
    },
    {
        id: 6,
        name:"Theif",
        type:"adventurer",
        element:"Lightning",
        attribute:["dps"],
        healthy_attack:"2",
        healthy_defense:"1",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"Whats yours is mine",
        description:"",
        turn_cost:"0",
        hand_cost:"0",
        effect:""
    },
    {
        id: 7,
        name:"Brigand",
        type:"adventurer",
        element:"Lightning",
        attribute:["dps", "swordplay"],
        healthy_attack:"2",
        healthy_defense:"1",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"I'll crush you",
        description:"",
        turn_cost:"0",
        hand_cost:"0",
        effect:""
    },
    {
        id: 8,
        name:"Acolyte",
        type:"adventurer",
        element:"Lightning",
        attribute:["dps", "mage"],
        healthy_attack:"2",
        healthy_defense:"1",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"I'll crush you",
        description:"",
        turn_cost:"0",
        hand_cost:"0",
        effect:""
    },
    {
        id: 9,
        name:"Raya Shain",
        type:"adventurer",
        element:"Fire",
        attribute:["dps", "journeyman", "mage"],
        healthy_attack:"4",
        healthy_defense:"3",
        injured_attack:"2",
        injured_defense:"1",
        flavor:"The Rose Arsonist makes her way on the scene",
        description:"",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 10,
        name:"Renierre Huvoir",
        type:"adventurer",
        element:"Water",
        attribute:["healer","mage", "apothacary", "master"],
        healthy_attack:"2",
        healthy_defense:"4",
        injured_attack:"2",
        injured_defense:"2",
        flavor:"Rest warrior. You won't beat anyone if you don't take care of your wounds",
        description:"At the beginning of your turn you can spend 1 mana point to heal an adventurer",
        turn_cost:"5",
        hand_cost:"1",
        effect:""
    },
    {
        id: 11,
        name:"Jamie Jade Eye",
        type:"adventurer",
        element:"Earth",
        attribute:["tank","swordplay", "master"],
        healthy_attack:"3",
        healthy_defense:"3",
        injured_attack:"2",
        injured_defense:"2",
        flavor:"Get behind me, I'll protect you all. I bet my life on it.",
        description:"At the beginning of your turn you can spend 1 mana point to heal an adventurer",
        turn_cost:"5",
        hand_cost:"1",
        effect:""
    },
    {
        id: 12,
        name:"Teruko Kazuma",
        type:"adventurer",
        element:"Wind",
        attribute:["dps","mage", "summoner", "master"],
        healthy_attack:"2",
        healthy_defense:"2",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"Get behind me, I'll protect you all. I bet my life on it.",
        description:"When you put this adventurer in play, You may search your deck for a card with the beast attribute and add it to your hand. Shuffle the deck afterwards.",
        turn_cost:"5",
        hand_cost:"1",
        effect:""
    },
    {
        id: 12,
        name:"Dragon Ratatoskr",
        type:"adventurer",
        element:"Wind",
        attribute:["dps","beast", "dragon", "legendary"],
        healthy_attack:"5",
        healthy_defense:"5",
        injured_attack:"3",
        injured_defense:"3",
        flavor:"Behold the majesty of a true dragon",
        description:"This creature can only be sent to battle in the same team as a summoner",
        turn_cost:"5",
        hand_cost:"1",
        effect:""
    },
    {
        id: 13,
        name:"Avian Gilder",
        type:"adventurer",
        element:"Wind",
        attribute:["dps","beast", "avian", "master"],
        healthy_attack:"3",
        healthy_defense:"3",
        injured_attack:"2",
        injured_defense:"2",
        flavor:"Behold the majesty of a true dragon",
        description:"This creature can only be sent to battle in the same team as a summoner",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 14,
        name:"Steel Sword",
        type:"equipment",
        element:"Fire",
        attribute:["dps","swordplay"],
        healthy_attack:"2",
        healthy_defense:"0",
        injured_attack:"0",
        injured_defense:"0",
        flavor:"Hyaahhh!",
        description:"",
        turn_cost:"2",
        hand_cost:"0",
        effect:""
    },
    {
        id: 15,
        name:"Dragon Sword",
        type:"equipment",
        element:"Fire",
        attribute:["dps","swordplay", "master"],
        healthy_attack:"3",
        healthy_defense:"0",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"Behold that expert craftsmanship. That is one fine sword.",
        description:"If this card is equiped to a fire adventure it grants an additional +1 to attack",
        turn_cost:"2",
        hand_cost:"0",
        effect:""
    },
    {
        id: 16,
        name:"Iron Shield",
        type:"equipment",
        element:"Earth",
        attribute:["tank","shield"],
        healthy_attack:"0",
        healthy_defense:"2",
        injured_attack:"0",
        injured_defense:"1",
        flavor:"A shield can save your life.",
        description:"",
        turn_cost:"2",
        hand_cost:"0",
        effect:""
    },
    {
        id: 17,
        name:"Grand Aegis",
        type:"equipment",
        element:"Earth",
        attribute:["tank","shield", "master"],
        healthy_attack:"0",
        healthy_defense:"4",
        injured_attack:"0",
        injured_defense:"3",
        flavor:"The Legendary defender can reflect even the mightiest blow",
        description:"",
        turn_cost:"2",
        hand_cost:"0",
        effect:""
    },
    {
        id: 18,
        name:"Ruby Wand",
        type:"equipment",
        element:"Fire",
        attribute:["dps","rod", "mage"],
        healthy_attack:"2",
        healthy_defense:"2",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"Behold the fiery blaze",
        description:"",
        turn_cost:"2",
        hand_cost:"0",
        effect:""
    },
    {
        id: 19,
        name:"Obsidian Wand",
        type:"equipment",
        element:"Lightning",
        attribute:["dps","rod", "mage"],
        healthy_attack:"2",
        healthy_defense:"2",
        injured_attack:"1",
        injured_defense:"0",
        flavor:"Behold the raging thunder",
        description:"",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 20,
        name:"Blacksmith Orion",
        type:"Client",
        element:"Fire",
        attribute:["swordplay"],
        healthy_attack:"0",
        healthy_defense:"0",
        injured_attack:"0",
        injured_defense:"0",
        flavor:"Behold the raging thunder",
        description:"While this client is in play all equipment with the 'swordplay' attribute gain an additional +1 attack.",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 21,
        name:"Armorer Delvin",
        type:"Client",
        element:"Earth",
        attribute:["swordplay"],
        healthy_attack:"0",
        healthy_defense:"0",
        injured_attack:"0",
        injured_defense:"0",
        flavor:"Behold the raging thunder",
        description:"While this client is in play, all of your in play equipment with the 'shield' attribute gain an additional +1 defense.",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 22,
        name:"Armorer Delvin",
        type:"Client",
        element:"Earth",
        attribute:["swordplay"],
        healthy_attack:"0",
        healthy_defense:"0",
        injured_attack:"0",
        injured_defense:"0",
        flavor:"Behold the raging thunder",
        description:"While this client is in play, all of your in play equipment with the 'shield' attribute gain an additional +1 defense.",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 23,
        name:"Merchant Bridgette",
        type:"Client",
        element:"Wind",
        attribute:["swordplay"],
        healthy_attack:"0",
        healthy_defense:"0",
        injured_attack:"0",
        injured_defense:"0",
        flavor:"Behold the raging thunder",
        description:"While this client is in play, if you send out an adventurer that is unopposed, you may draw a card at the end of the showdown.",
        turn_cost:"3",
        hand_cost:"0",
        effect:""
    },
    {
        id: 24,
        name:"Fire Ball",
        type:"Technique",
        element:"Fire",
        attribute:["mage"],
        flavor:"Behold the raging thunder",
        description:"Target: Adventurer or Beast opposed to the user. Deal one damage to the target",
        mana_cost:["Fire", ""],
        effect:""
    },
    {
        id: 25,
        name:"Earthly Trap",
        type:"Technique",
        element:"Earth",
        attribute:["mage"],
        flavor:"Behold the raging thunder",
        description:"Target: Adventurer or Beast opposed to the user. Move the target from the battlefield back to the field",
        mana_cost:["Earth", ""],
        effect:""
    },
    {
        id: 26,
        name:"Lightning Ball",
        type:"Technique",
        element:"Lightning",
        attribute:["mage"],
        flavor:"Behold the raging thunder",
        description:"Target: Adventurer or Beast opposed to the user. Deal one damage to the target",
        mana_cost:["Earth", ""],
        effect:""
    },
]